name: bar

on: 
  workflow_run:
    workflows:
      - foo
    types:
      - completed

jobs:
  workflow2:
    name: workflow 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: echo bar