# deploy to blob storage =>
name: Build and deploy the app to the Azure Blob Storage

# First workflow to run
on:
  push:
    branches:
      - development
env:
  AZURE_WEBAPP_PACKAGE_PATH: ui/react-ui
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: npm install and build
        run: |
          cd ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          npm install
          CI='' npm run build
      - name: Upload To Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/build
          container_name: $web
          connection_string: ${{secrets.BLOB_STORAGE_CONNECTION_STRING}}
      # Trigger deploy functions workflow
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-deploy-functions
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}': 
