name: foo

on: [push]

jobs:
  workflow1:
    name: workflow 1
    runs-on: ubuntu-latest
    steps:
      - name: wait two minutes
        run: |
          echo foo
          sleep 120
          echo foo end