name: foo

on: [push]

jobs:
  workflow1:
    name: workflow 1
    runs-on: ubuntu-latest
    steps:
      - name: wait one minute
        run: |
          echo foo
          sleep 60
          echo foo end