name: Serverless-Artillery performance test users-userid-tasks

# Run every time a new commit is pushed to the developemtn branch
# TODO: Actually change this to not be on every push
on: [push]

jobs:
  slsart-perf:
    name: slsart performance test users-userid-tasks
    runs-on: ubuntu-latest
    env:
      STAGE_NAME: u-uid-t
    steps:
      # Checkout a copy of the code
      - name: Checkout code
        uses: actions/checkout@v2
      # Install node on the VM
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      # Configure the AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # Install serverless-artillery
      - name: Install serverless and serverless-artillery
        run: |
          npm install -g serverless@1.38.0
          npm install -g serverless-artillery
      # Run serverless-artillery test
      - name: deploy
        run: slsart deploy --stage $STAGE_NAME --region us-west-2
      - name: invoke
        run: |
          slsart invoke -p test/serverless-artillery/serverless-artillery-test-users-id-tasks-api.yml --region us-west-2 --stage $STAGE_NAME > test/results/slsart-users-uid-tasks-results.json
      - name: remove
        run: slsart remove --stage $STAGE_NAME --region us-west-2
      # Get current date and time
      # Outputs date
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%F %T')"
      # Rename the results
      - name: Rename results json
        run: |
          mkdir test/results/upload
          cp test/results/slart-users-uid-tasks-results.json "/test/results/upload/serverless-artillery ${{ steps.date.outputs.date }}.json"