name: Serverless-Artillery performance test users-userid-tasks

# Run every time a new commit is pushed to development branch
on: [push]

jobs:
  check-bats-version:
    name: Check bats version
    runs-on: ubuntu-latest
    steps:
      # Checkout a copy of the code
      - name: Checkout code
        uses: actions/checkout@v2
      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      # Install bats and check version
      - run: npm install -g bats
      - run: bats -v
      # Test reading secrets
      - name: get test secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: echo "$TEST_SECRET"