# This is a basic workflow to help you get started with Actions

name: serverless-artillery-action-users-id-tasks-id-api

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #set up node js
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - run: npm install
      - run: npm test

      

      

  #upload:    
    #runs-on: ubuntu-latest
      #steps:
        #- name: Upload S3
          #uses: shallwefootball/upload-s3-action@v1.1.3
