name: sql injection test for users/userid PUT

on:
  push:
    branches:
      - development

jobs:
  PUT-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: create a test user to run the PUT request on it
        run: |
          curl -v -X POST -d '{"firstName": "injection-user-userid-test", "lastName": "injection-user-userid-test", "email": "injection-user-userid-test"}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users > test/security/sql-injection/sql-injection-users-userid-put.json
      - name: reading the created userId
        id: userId
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: test/security/sql-injection/sql-injection-users-userid-put.json
          prop_path: 'userId'
      - name: "user with id: ${{steps.userId.outputs.prop}} created"
        run: echo "userId:" ${{steps.userId.outputs.prop}} 
      - name: "update user ${{steps.userId.outputs.prop}} with this sql injection input: 'hacked'; DELETE FROM users WHERE userId = ${{steps.userId.outputs.prop}}; -- "
        run: |
          curl -v -X PUT -d '{"firstName": "'oops'; DELETE FROM users WHERE userId = ${{steps.userId.outputs.prop}}; -- "}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/${{steps.userId.outputs.prop}}
      - name: making sure that sql injection statement wasn't successfully injected. get user ${{steps.userId.outputs.prop}}
        run: |
          curl -v -X GET https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/${{steps.userId.outputs.prop}} > test/security/sql-injection/sql-injection-users-userid-put.json
      - name: read the output of GET request
        id: getUserId
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: test/security/sql-injection/sql-injection-users-userid-put.json
          prop_path: 'userId'
      - name: "user with id: ${{steps.getUserId.outputs.prop}} retrieved from database"
        run: echo "user retrieved from database with id:" ${{steps.getUserId.outputs.prop}} 
      - name: Remove the output file
        uses: JesseTG/rm@v1.0.2
        with:
          path: test/security/sql-injection/sql-injection-users-userid-put.json