name: Web UI Load Test for /users/{user_id}

on:
  push:
    branches:
      - development/yaholl/sprint6

env:
  NODE_VERSION: "14"
  UI_TESTS_PATH: "./test/serverless-artillery"
  UI_RESULTS_USERS_FILE_PATH: "./test/results/ui-test-results/users-id/load-tests"

jobs:
  ui-test-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true

      - name: Run Load Test
        run: |
          pushd ${{ env.UI_TESTS_PATH }}
          npm install
          node sa-test-users-id-v2.js
          popd

      - name: Refresh Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --destination screenshots \
              --source ${{ env.UI_RESULTS_USERS_FILE_PATH }} \
              --connection-string "${{secrets.BLOB_STORAGE_CONNECTION_STRING}}" \
              --pattern *.png