name: Web UI Test for /users/{user_id}

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: "14"
  UI_TESTS_PATH: "./test/ui"
  UI_RESULTS_USERS_FILE_PATH: "./test/results/ui-test-results/users-id/"

jobs:
  ui-test-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true

      - name: Take a screenshot
        run: |
          pushd ${{ env.UI_TESTS_PATH }}
          npm install
          node ui-tests-user-id.js
          popd

      - name: Upload screenshot to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --destination screenshots \
              --source ${{ env.UI_RESULTS_USERS_FILE_PATH }} \
              --connection-string "${{secrets.BLOB_STORAGE_CONNECTION_STRING}}" \
              --pattern *.png
